// <auto-generated />
namespace Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddMyStadiumToMatch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMyStadiumToMatch));
        
        string IMigrationMetadata.Id
        {
            get { return "201711271808038_AddMyStadiumToMatch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
